cmake_minimum_required(VERSION 3.14)

project(DREAMPlace LANGUAGES CXX)
# 启用后，CMake 会在生成的 makefile 中包含更多的详细信息，方便调试和查看编译过程中的具体命令。
set(CMAKE_VERBOSE_MAKEFILE ON)

if (CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
    set (CMAKE_INSTALL_PREFIX "${CMAKE_CURRENT_SOURCE_DIR}/install" CACHE PATH "Prefix prepended to install directories" FORCE )
endif()
message(STATUS "CMAKE_INSTALL_PREFIX: ${CMAKE_INSTALL_PREFIX}")

if(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE "Release" CACHE STRING
        "Choose the type of build, options are: Debug Release."
        FORCE)
endif(NOT CMAKE_BUILD_TYPE)
# statue 用于输出信息
message(STATUS "CMAKE_BUILD_TYPE: ${CMAKE_BUILD_TYPE}")

# This is a dirty fix for CMake on some machines that generates default CXX standard and override the custom settings, 
# because CUDA does not support C++17 and higher. 
# You can check the CMAKE_CXX_FLAGS in CMakeCache.txt to verify the issue. 
if(CMAKE_CXX_FLAGS)
# string(REGEX REPLACE "pattern" "replacement" output input)，
# 使用正则表达式将 CMAKE_CXX_FLAGS 中的 -std=c++ 标准标志移除
# -std=： 匹配 -std= 的固定文本部分。 
# c\+\+： 匹配 c++，其中 + 是正则表达式中的特殊字符，需要用 \ 转义。
#([0-9a-z]+)： 捕获组，匹配一个或多个数字 (0-9) 或小写字母 (a-z)。

string(REGEX REPLACE "-std=c\\+\\+([0-9a-z]+)" " " CMAKE_CXX_FLAGS_INIT ${CMAKE_CXX_FLAGS})
endif(CMAKE_CXX_FLAGS)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS_INIT}" CACHE STRING "Flags used by the compiler during all build types." FORCE)


if(NOT CMAKE_CXX_ABI)
    set(CMAKE_CXX_ABI 0 CACHE STRING
        "Choose the value for _GLIBCXX_USE_CXX11_ABI, options are: 0|1."
        FORCE)
endif(NOT CMAKE_CXX_ABI)
message(STATUS "CMAKE_CXX_ABI: _GLIBCXX_USE_CXX11_ABI=${CMAKE_CXX_ABI}")
#-D_GLIBCXX_USE_CXX11_ABI=1：如果 CMAKE_CXX_ABI 为 1，则使用 新的 C++11 ABI 特性。  否则，使用旧的 C++98 ABI 特性。
add_definitions(-D_GLIBCXX_USE_CXX11_ABI=${CMAKE_CXX_ABI})

#它允许你引用相对于当前目录的文件和目录，而不是相对于包含它的文件的目录。
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_CURRENT_SOURCE_DIR}/cmake")


# CUDA_USE_STATIC_CUDA_RUNTIME：这是一个控制 CUDA 运行时库链接方式的变量。
# ON：使用静态链接的 CUDA 运行时库。
# OFF：使用动态链接的 CUDA 运行时库。
# for CUDA, must be put before finding PyTorch  
# link dynamic libraries rather than static ones 

set(CUDA_USE_STATIC_CUDA_RUNTIME OFF)


# critical for cuda_add_library, as we need to turn off -O flags 
# to make sure the symbols generated by nvcc and gcc are the same 

# CUDA_PROPAGATE_HOST_FLAGS：这是一个控制是否将主机编译器的编译标志传递给 NVCC 的变量。
# ON：将主机编译器的编译标志传递给 NVCC。
# 当 CUDA_PROPAGATE_HOST_FLAGS 设置为 ON 时，CMake 会将主机编译器（如 GCC 或 Clang）的编译标志（如优化标志、调试标志等）
# 传递给 NVCC。这意味着 NVCC 在编译 CUDA 代码时，会使用与主机编译器相同的编译标志。
# OFF：不将主机编译器的编译标志传递给 NVCC。

set(CUDA_PROPAGATE_HOST_FLAGS ON)


# required for executable to run at the install directory 
# it will change the RPATH when installing 

#RPATH（运行时库搜索路径），RPATH 是可执行文件或共享库中的一个字段，指定在运行时搜索共享库的路径。
#通过设置 RPATH，可以确保在运行时找到所需的共享库，而不需要依赖环境变量 LD_LIBRARY_PATH。
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)

# we can us function in cmake/TorchExtension.cmake
include(cmake/TorchExtension.cmake)

set(CMAKE_CXX_STANDARD 17)
# 如果编译器不支持 C++17 标准，CMake 将会报错
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# without this, clang will complain about linking 
#set(CMAKE_CXX_VISIBILITY_PRESET hidden)

# 位置无关代码（Position Independent Code, PIC）是一种编译选项，
# 使生成的代码可以在内存中的任何位置执行，而不需要依赖固定的地址。这对于创建共享库（shared libraries）非常重要，
# 因为共享库在加载时可能会被映射到内存中的不同地址。
set_property(GLOBAL PROPERTY POSITION_INDEPENDENT_CODE TRUE)

find_package(OpenMP REQUIRED)
#find_program(PYTHON "python" REQUIRED)
find_package(ZLIB REQUIRED)

# 表示不使用 Boost 自带的 CMake 配置文件，而是使用 CMake 自己的查找机制来查找 Boost 库。
set(Boost_NO_BOOST_CMAKE TRUE)
find_package(Boost 1.55.0 REQUIRED)
message(STATUS "Boost_INCLUDE_DIRS = ${Boost_INCLUDE_DIRS}")


set(CUDA_TOOLKIT_ROOT_DIR /usr/local/cuda)
find_package(CUDA REQUIRED)

find_package(Cairo)
message(STATUS "Cairo: ${CAIRO_INCLUDE_DIRS}")
message(STATUS "Cairo: ${CAIRO_LIBRARIES}")
# get_filename_component：这是一个 CMake 命令，用于获取文件或目录的组成部分
# ABSOLUTE：这是一个选项，表示获取输入路径的绝对路径
get_filename_component(OPS_DIR ${CMAKE_CURRENT_SOURCE_DIR}/dreamplace/ops ABSOLUTE)
get_filename_component(UTILITY_LIBRARY_DIRS ${CMAKE_CURRENT_BINARY_DIR}/dreamplace/ops/utility ABSOLUTE)
message(STATUS "OPS_DIR ${OPS_DIR}")
message(STATUS "UTILITY_LIBRARY_DIRS ${UTILITY_LIBRARY_DIRS}")

# thirdparty libraries 
# flute for steiner tree generation 
# find_path：这是一个 CMake 命令，用于查找包含指定文件的目录。
# The PATHS option is used to specify the directory paths that the find_path command should search when looking for a file.
find_path(FLUTE_INCLUDE_DIRS flute.hpp PATHS ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/*)
# {CMAKE_CURRENT_BINARY_DIR}：这是当前构建目录的路径，通常是CMake生成的中间文件、Makefiles等的存放目录。通常是build目录。
# string(REPLACE <find> <replace> <output_variable> <input_string>)

string(REPLACE ${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_CURRENT_BINARY_DIR} FLUTE_LINK_DIRS ${FLUTE_INCLUDE_DIRS})
message(STATUS "FLUTE_INCLUDE_DIRS ${FLUTE_INCLUDE_DIRS}")
message(STATUS "FLUTE_LINK_DIRS ${FLUTE_LINK_DIRS}")

# include_directories：这是一个 CMake 函数，用于添加头文件搜索路径。
include_directories(${FLUTE_INCLUDE_DIRS})
# Limbo for parsers 
set(LIMBO_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/Limbo)
message(STATUS "LIMBO_SOURCE_DIR ${LIMBO_SOURCE_DIR}")

set(LIMBO_BINARY_DIR ${CMAKE_CURRENT_BINARY_DIR}/thirdparty/Limbo)
message(STATUS "LIMBO_BINARY_DIR ${LIMBO_BINARY_DIR}")

if(CUDA_FOUND)
  if (${CUDA_VERSION_MAJOR} VERSION_GREATER_EQUAL "11")
    set(CUB_DIR ${CUDA_INCLUDE_DIRS})
  else()
    set(CUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/cub)
  endif()
endif()
message(STATUS "CUB_DIR ${CUB_DIR}")

# munkres-cpp for Hungarian algorithm 
set(MUNKRES_CPP_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/munkres-cpp/src)
set(MUNKRES_CPP_LINK_DIRS ${CMAKE_CURRENT_BINARY_DIR}/thirdparty/munkres-cpp)
message(STATUS "MUNKRES_CPP_INCLUDE_DIRS ${MUNKRES_CPP_INCLUDE_DIRS}")
message(STATUS "MUNKRES_CPP_LINK_DIRS ${MUNKRES_CPP_LINK_DIRS}")

# lemon for network flow algorithms 
# find_path：这是 CMake 提供的一个命令，用于查找指定文件的路径，并将该路径赋给一个变量。它会在你指定的目录中搜索该文件。
find_path(LEMON_SOURCE_DIR lemon PATHS ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/Limbo/limbo/thirdparty/* 
	NO_DEFAULT_PATH
	)

set(LEMON_INCLUDE_DIRS "${LEMON_SOURCE_DIR}")
# string(REPLACE <old_string> <new_string> <output_variable> <input_string>)

string(REPLACE ${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_CURRENT_BINARY_DIR} LEMON_BINARY_DIR ${LEMON_SOURCE_DIR})
# list 是 CMake 中用来处理列表的命令，APPEND 表示将新的元素添加到列表的末尾。
list(APPEND LEMON_INCLUDE_DIRS "${LEMON_BINARY_DIR}")
set(LEMON_LINK_DIRS ${LEMON_BINARY_DIR}/lemon)
message(STATUS "LEMON_INCLUDE_DIRS ${LEMON_INCLUDE_DIRS}")
message(STATUS "LEMON_LINK_DIRS ${LEMON_LINK_DIRS}")

set(OPENTIMER_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/OpenTimer)
message(STATUS "OPENTIMER_SOURCE_DIR ${OPENTIMER_SOURCE_DIR}")
set(OPENTIMER_BINARY_DIR ${CMAKE_CURRENT_BINARY_DIR}/thirdparty/OpenTimer)
message(STATUS "OPENTIMER_BINARY_DIR ${OPENTIMER_BINARY_DIR}")
include_directories(${OPENTIMER_SOURCE_DIR})

if (CUDA_FOUND)
  if (NOT CMAKE_CUDA_ARCHITECTURES)
    set(CMAKE_CUDA_ARCHITECTURES 6.0 6.1 7.0)
    if (${CUDA_VERSION_MAJOR} VERSION_GREATER "9")
      list(APPEND CMAKE_CUDA_ARCHITECTURES 7.5)
    endif(${CUDA_VERSION_MAJOR} VERSION_GREATER "9")
    if (${CUDA_VERSION_MAJOR} VERSION_GREATER "10")
      list(APPEND CMAKE_CUDA_ARCHITECTURES 8.0)
      # arch 8.6 removed for compatability with 3090
      # list(APPEND CMAKE_CUDA_ARCHITECTURES 8.6)
    endif(${CUDA_VERSION_MAJOR} VERSION_GREATER "10")
  endif(NOT CMAKE_CUDA_ARCHITECTURES)

  # for cuda_add_library
  # cuda_select_nvcc_arch_flags 是一个 CMake 自带的宏，它用来根据所设置的 CUDA 架构（CMAKE_CUDA_ARCHITECTURES）选择适当的 nvcc 编译器标志。
  cuda_select_nvcc_arch_flags(CUDA_ARCH_FLAGS ${CMAKE_CUDA_ARCHITECTURES})
  message(STATUS "CUDA_ARCH_FLAGS: ${CUDA_ARCH_FLAGS}")
  # CUDA_NVCC_FLAGS 列表变量   ${CUDA_ARCH_FLAGS}一个变量
  list(APPEND CUDA_NVCC_FLAGS ${CUDA_ARCH_FLAGS} --compiler-options;-fPIC)
endif(CUDA_FOUND)



configure_file(${CMAKE_CURRENT_SOURCE_DIR}/dreamplace/configure.py.in ${CMAKE_CURRENT_BINARY_DIR}/dreamplace/configure.py)
# 将名为 thirdparty 的子目录添加到 CMake 项目中。这个子目录通常包含外部依赖项或第三方库。
# CMake 会查找 thirdparty 目录中的 CMakeLists.txt 文件并执行其内容。
add_subdirectory(thirdparty)
add_subdirectory(dreamplace)
add_subdirectory(unittest)
add_subdirectory(benchmarks)
add_subdirectory(test)
#
install(FILES ${CMAKE_CURRENT_BINARY_DIR}/dreamplace/configure.py DESTINATION dreamplace)
